version: '3.8'

services:
  # PostgreSQL for DB
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Host:5433 → Container:5432
    restart: unless-stopped

  # Spring Boot API
  api:
    build: .
    container_name: spring-api-container
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    restart: unless-stopped

# Volumes
volumes:
  db_data: