version: '3.8'

services:
  # PostgreSQL for DB
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  # Spring Boot API
  api:
    build: .
    container_name: spring-api-container
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    restart: unless-stopped

  # Keycloak for DB
  keycloak-db:
    image: postgres
    container_name: keycloak-db-container
    environment:
      POSTGRES_DB: db-keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 123
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped

  # Keycloak Identity Server
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    container_name: keycloak-container
    command: ['start-dev']  # Dev mode, no SSL required
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 123
    depends_on:
      - keycloak-db
    ports:
      - "8080:8080"
      - "8443:8443"
    restart: unless-stopped

# Volumes
volumes:
  db_data:
  keycloak_data: